version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: production
      API_PORT: 8000
      DATABASE_URL: ${DATABASE_URL} # Sesuaikan dengan .env
    volumes:
      - .:/usr/src/app # Untuk mengembangkan aplikasi dengan lebih mudah
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: 207dbe5d8941016a
      POSTGRES_DB: db-finalproject
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
