version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
      - PORT=8000
    env_file:
      - .env.prod
    ports:
      - "8000:8000"
    command: ["npm", "run", "dev"]
    profiles:
      - dev
    depends_on:
      - seed

  app-prod:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=8000
    env_file:
      - .env.prod
    ports:
      - "8000:8000"
    command: ["node", "dist/server.js"]
    profiles:
      - prod
    depends_on:
      - seed
